language: java
install: mvn install -DskipTests=true
script: mvn test
sudo: required
dist: trusty
jdk:
        - oraclejdk8
        - oraclejdk7

os:
  - linux
  - windows

notifications:
  email:
    on_success: never # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always